#include<bits/stdc++.h>

using namespace std;

/* 
Destructors are just like constructors are used to destroy the the objects .
Destructors are executed when-
 1)when the pgm finishes execution
 2)when the scope of the {} ends for the local variable
 3)when you call the delete operator 
Destructor is generated by the compiler when no destructor is specified.
1-It has same name as class and has no retrun type. 2-~ symbol is peceded with the name .
3-It has no parameters .                            4-A pgm can not have more than one destructor
*/

class Hello
{
public:
	Hello()  // constructor
	{
		cout<<"Constructor called\n";
	}
	~Hello() // destructor
	{
		cout<<"Destructor called\n";
	}
	void display()
	{
		cout<<"Hello World\n";
	}

};

int main(){

	Hello obj;
	obj.display();

	return 0;
}